In [1]:
import numpy as np

In [2]:
import statsmodels.api as sm


In [3]:
spector_data = sm.datasets.spector.load()


In [4]:
spector_data.exog = sm.add_constant(spector_data.exog, prepend=False)

In [5]:
mod = sm.OLS(spector_data.endog, spector_data.exog)

In [6]:
res = mod.fit()

In [7]:
print(res.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.416
Model:                            OLS   Adj. R-squared:                  0.353
Method:                 Least Squares   F-statistic:                     6.646
Date:                Wed, 07 Feb 2024   Prob (F-statistic):            0.00157
Time:                        04:58:26   Log-Likelihood:                -12.978
No. Observations:                  32   AIC:                             33.96
Df Residuals:                      28   BIC:                             39.82
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.4639      0.162      2.864      0.0

In [1]:
%timeit sum(range(10000000))

376 ms ± 10.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [2]:
import numpy as np

In [3]:
%timeit np.sum(np.arange(10000000))

20.2 ms ± 505 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
import numpy as np

In [5]:
# 1D

x=np.array([1,2,3])

In [6]:
print(x)

[1 2 3]


In [7]:
type(x)

numpy.ndarray

In [8]:
# 2D

y=np.array([[1,2,3],[4,5,6]])

In [9]:
print(y)

[[1 2 3]
 [4 5 6]]


In [14]:
# 3D

z=np.ones((4,3,2),dtype=int)

In [15]:
print(z)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


In [13]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [16]:
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [21]:
x=np.ones((4,3,2))

In [22]:
print(x.itemsize)
print(x.dtype)
print(x.size)
print(x.shape)
print(x.ndim)

8
float64
24
(4, 3, 2)
3


In [28]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [30]:
np.arange(2,6)

array([2, 3, 4, 5])

In [31]:
np.arange(1,6,2)

array([1, 3, 5])

In [27]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [34]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [33]:
np.ones((4,3,2)) + 3

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [36]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [37]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [43]:
print(a[1,2])

7


In [39]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [40]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [41]:
np.arange(1,10).reshape(5,2)

ValueError: cannot reshape array of size 9 into shape (5,2)

In [42]:
np.arange(1,17).reshape(2,2,2,2)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [44]:
a=np.array([3,4,5,6])
for i in np.nditer(a) :
    print(i)
for i in a :
    print(i)

3
4
5
6
3
4
5
6


In [46]:
a=np.array([[3,4,5,6],[7,8,9,10]])
for i in np.nditer(a) :
    print(i)
for i in a :
    print(i)

3
4
5
6
7
8
9
10
[3 4 5 6]
[ 7  8  9 10]


In [47]:
x=np.array([5,6,7,8])
for i,v in np.ndenumerate(x) :
    print(i,v)

(0,) 5
(1,) 6
(2,) 7
(3,) 8


In [48]:
c=np.arange(6).reshape(2,3) 
d=np.arange(6,12).reshape(2,3)
print(c)
print(d)
np.concatenate((c,d),axis=0)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [49]:
c=np.arange(6).reshape(2,3) 
d=np.arange(6,12).reshape(2,3)
print(c)
print(d)
np.concatenate((c,d),axis=1)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [51]:
arr=np.array([1,2,3,4,5,6])
new=np.array_split(arr,3)
new

[array([1, 2]), array([3, 4]), array([5, 6])]

In [52]:
arr=np.array([1,2,3,4,5,6])
new=np.array_split(arr,3)
new[1]

array([3, 4])

In [53]:
arr=np.array([1,2,3,4,5,6])
new=np.array_split(arr,4)
new

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [54]:
arr=np.array([1,2,3,4,5,6])
new=np.array_split(arr,5)
new

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]

In [55]:
arr=np.array([1,2,3,4,5,6])
new=np.array_split(arr,6)
new

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]

In [56]:
arr=np.array([1,2,3,4,5,6])
new=np.array_split(arr,7)
new

[array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([], dtype=int32)]

In [57]:
arr=np.array([1,2,3,4,5,6])
new=np.array_split(arr,8)
new

[array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([], dtype=int32),
 array([], dtype=int32)]

In [59]:
# where

b=np.array([58,69,15,43,66,44,88])
np.where(b>50)

(array([0, 1, 4, 6], dtype=int64),)

In [73]:
np.where(b>50,0,b)

array([ 0,  0, 15, 43,  0, 44,  0])

In [74]:
a=np.array([3,4,1,6,2])
print(a)
np.sort(a)


[3 4 1 6 2]


array([1, 2, 3, 4, 6])

In [75]:
a

array([3, 4, 1, 6, 2])

In [76]:
np.sort(a)[::-1]

array([6, 4, 3, 2, 1])